### ISSUE TITLE
pip install with python2 is broken

### ISSUE THREAD

**Issue by mbiokyle29** [biosustain/potion-client#10]
I tried installing the v2 potion client (which looks absolutely fabulous) in python2 and pip fails:

```
$ pip install Potion-client
Collecting Potion-client
  Using cached Potion-client-2.0.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): jsonschema>=2.4 in ./venv/lib/python2.7/site-packages (from Potion-client)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.5 in ./venv/lib/python2.7/site-packages (from Potion-client)
Requirement already satisfied (use --upgrade to upgrade): six in ./venv/lib/python2.7/site-packages (from Potion-client)
Requirement already satisfied (use --upgrade to upgrade): functools32 in ./venv/lib/python2.7/site-packages (from jsonschema>=2.4->Potion-client)
Installing collected packages: Potion-client
  Running setup.py install for Potion-client ... error
    Complete output from command /home/kyle/Dev/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wPs324/Potion-client/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-IP0d9z-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/kyle/Dev/venv/include/site/python2.7/Potion-client:
    running install
    running build
    running build_py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wPs324/Potion-client/setup.py", line 36, in <module>
        'License :: OSI Approved :: MIT License'
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/kyle/Dev/venv/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/kyle/Dev/venv/local/lib/python2.7/site-packages/setuptools/command/build_py.py", line 51, in run
        self.build_packages()
      File "/usr/lib/python2.7/distutils/command/build_py.py", line 373, in build_packages
        self.build_module(module, module_file, package)
      File "/home/kyle/Dev/venv/local/lib/python2.7/site-packages/setuptools/command/build_py.py", line 71, in build_module
        package)
      File "/usr/lib/python2.7/distutils/command/build_py.py", line 334, in build_module
        "'package' must be a string (dot-separated), list, or tuple")
    TypeError: 'package' must be a string (dot-separated), list, or tuple

    ----------------------------------------
Command "/home/kyle/Dev/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wPs324/Potion-client/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-IP0d9z-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/kyle/Dev/venv/include/site/python2.7/Potion-client" failed with error code 1 in /tmp/pip-build-wPs324/Potion-client/
```

If you remove the encoding setting at the top, everything seems to work smoothly (pip install and testing). But it breaks stuff with python3 (mostly with tests running).

There is no issue with installing on python3 though, so it is clearly a unicode handling thing. There are a few mentions of these issues in pip and setuptools bug reports.

https://github.com/pypa/pip/issues/1441
https://bugs.python.org/issue13943

**Comment by lyschoening** [comment]
Yes, it was that unicode issue with distutils. I've released a fix in v2.0.1
